// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = {
    controller: function() {
      var attrs;
      return attrs = {
        form: function() {},
        keydown: function(e) {
          var callback;
          callback = function(ev) {
            if (ev.keyCode === 13) {
              return console.log('enter key');
            }
          };
          return e.addEventListener('keydown', callback, false);
        },
        tasks: [
          {
            id: 1,
            name: 'Adding GA'
          }, {
            id: 2,
            name: 'Install your js framework'
          }, {
            id: 3,
            name: 'write code..'
          }
        ]
      };
    },
    view: function(ctrl) {
      var content, form, i, len, ref, task, tasks;
      content = [];
      tasks = [];
      form = m('form.task_form', {
        config: ctrl.form
      }, m("input[type='text']", {
        placeholder: 'write a task...',
        config: ctrl.keydown
      }));
      ref = ctrl.tasks;
      for (i = 0, len = ref.length; i < len; i++) {
        task = ref[i];
        tasks.push(m('.task', m("input[type='checkbox']"), m('span.name', task.name)));
      }
      content.push(tasks);
      content.push(form);
      return m('.container', m('.wrapper', m('.header', m('h1', 'Todo App')), m('.content', content), m('.footer')));
    }
  };

  m.mount(document.body, app);

}).call(this);
